// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5WUbxD1zCeXGgRwkn497gL_nZbLVTcwY',
    appId: '1:662455252754:web:4b560a8d6e8fba8f5a25cb',
    messagingSenderId: '662455252754',
    projectId: 'api-rest-3babb',
    authDomain: 'api-rest-3babb.firebaseapp.com',
    databaseURL: 'https://api-rest-3babb-default-rtdb.firebaseio.com',
    storageBucket: 'api-rest-3babb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-n1JdKvnZgivOnDLbjXQj3WJS6RI_-Cc',
    appId: '1:662455252754:android:e2ec08120af4e9be5a25cb',
    messagingSenderId: '662455252754',
    projectId: 'api-rest-3babb',
    databaseURL: 'https://api-rest-3babb-default-rtdb.firebaseio.com',
    storageBucket: 'api-rest-3babb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8RI6_ddaLIzxyp3toNy4TRjAVandXUvQ',
    appId: '1:662455252754:ios:b5d119f11f775bae5a25cb',
    messagingSenderId: '662455252754',
    projectId: 'api-rest-3babb',
    databaseURL: 'https://api-rest-3babb-default-rtdb.firebaseio.com',
    storageBucket: 'api-rest-3babb.appspot.com',
    iosBundleId: 'com.example.mknBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8RI6_ddaLIzxyp3toNy4TRjAVandXUvQ',
    appId: '1:662455252754:ios:939be2beaa17bde85a25cb',
    messagingSenderId: '662455252754',
    projectId: 'api-rest-3babb',
    databaseURL: 'https://api-rest-3babb-default-rtdb.firebaseio.com',
    storageBucket: 'api-rest-3babb.appspot.com',
    iosBundleId: 'com.example.mknBank.RunnerTests',
  );
}
